---

- name: create directory
  file: path=/storage/prior/applications/mumble-bot-frontend state=directory

- name: copy files
  copy:
    src: "{{ item }}"
    dest: /storage/prior/applications/mumble-bot-frontend/
  with_items:
    - ../index.html
    - ../dist

- name: configure
  template:
    src: config.js.j2
    dest: '/storage/prior/applications/mumble-bot-frontend/config.js'
